# Generated by Django 3.0.4 on 2020-03-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnarie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='email',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='用户id'),
        ),
    ]
