# Generated by Django 3.0.4 on 2020-03-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200323_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
    ]
