# Generated by Django 3.0.4 on 2020-03-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_user_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
    ]
