# Generated by Django 3.0.4 on 2020-03-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200324_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='查看次数'),
        ),
        migrations.AddField(
            model_name='topic',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='查看次数'),
        ),
    ]
