# Generated by Django 3.0.4 on 2020-03-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('to_all', models.BooleanField(default=True, verbose_name='给所有人')),
                ('to_one_id', models.IntegerField(blank=True, null=True, verbose_name='给个人')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '系统通知',
                'verbose_name_plural': '系统通知',
                'db_table': 'sys_notice',
            },
        ),
    ]
