# Generated by Django 3.0.4 on 2020-03-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_sysnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(default=None, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=None, max_length=32, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default=None, max_length=32, verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default=None, max_length=32, verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=None, max_length=32, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(default=None, max_length=32, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('', '')], default='', max_length=8, verbose_name='性别'),
        ),
    ]
