# Generated by Django 3.0.4 on 2020-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200324_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='省份'),
        ),
    ]
