# Generated by Django 3.0.4 on 2020-03-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20200326_1107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questionnaire',
        ),
    ]
