# Generated by Django 3.0.4 on 2020-03-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_delete_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('name', models.CharField(max_length=128, verbose_name='问卷名')),
                ('brief', models.TextField(verbose_name='简介')),
            ],
            options={
                'verbose_name': '问卷',
                'verbose_name_plural': '问卷',
                'db_table': 'questionnaire',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireChoiceField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='序号')),
                ('field_id', models.IntegerField(verbose_name='题目id')),
                ('content', models.TextField(verbose_name='选项内容')),
            ],
            options={
                'db_table': 'questionnaire_choice_field',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_id', models.IntegerField(verbose_name='问卷id')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('is_multiple', models.BooleanField(default=False, verbose_name='多选')),
            ],
            options={
                'db_table': 'questionnaire_field',
            },
        ),
        migrations.CreateModel(
            name='QuestionnarieRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('email', models.EmailField(max_length=254, verbose_name='提交人邮箱')),
                ('questionnaire_id', models.IntegerField(verbose_name='问卷id')),
                ('field_id', models.IntegerField(verbose_name='题目id')),
                ('result', models.CharField(max_length=32, verbose_name='所选内容')),
            ],
            options={
                'db_table': 'questionnarie_record',
            },
        ),
    ]
