# Generated by Django 3.0.4 on 2020-03-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_questionnaire_questionnairechoicefield_questionnairefield_questionnarierecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questionnaire',
        ),
        migrations.DeleteModel(
            name='QuestionnaireChoiceField',
        ),
        migrations.DeleteModel(
            name='QuestionnaireField',
        ),
        migrations.DeleteModel(
            name='QuestionnarieRecord',
        ),
    ]
